### ISSUE TITLE
WebVTT parser incorrectly requires trailing newline

### ISSUE THREAD

**Issue by LukasKalbertodt** [mochi-neko/subtp#1]
```
WEBVTT

00:00:00.030 --> 00:00:03.210
foo bar
```

This file (without trailing newline!) fails to parse with `Parse error at 4:8: expected one of "\n", "\r", "\r\n", [_]`. A quick look at the WebVTT spec seems to indicate that a trailing newline is not required.

> 7. Zero or more [WebVTT cue blocks](https://www.w3.org/TR/webvtt1/#webvtt-cue-block) and [WebVTT comment blocks](https://www.w3.org/TR/webvtt1/#webvtt-comment-block) separated from each other by one or more [WebVTT line terminators](https://www.w3.org/TR/webvtt1/#webvtt-line-terminator).
> 8. Zero or more [WebVTT line terminators](https://www.w3.org/TR/webvtt1/#webvtt-line-terminator).

**Comment by bwkimmel** [comment]
I don't think this is correct. While the *file structure* may not require a line-terminator, each [cue block](https://www.w3.org/TR/webvtt1/#webvtt-cue-block) does:

> A **_WebVTT cue block_** consists of the following components, in the given order:
...
>    6. A [WebVTT line terminator](https://www.w3.org/TR/webvtt1/#webvtt-line-terminator).

So, given that the last thing in the file is a cue block, the file will naturally end in a line terminator.

**Comment by LukasKalbertodt** [comment]
Ah, yes it seems I was mistaken. Thanks!
